# Site settings
title: Jialong Blog
SEOTitle: 嘉龙的博客 | Jialong Blog
header-img: img/post-bg-desk.jpg
email: jialongfyd@gmail.com
description: "Every failure is leading towards success."
keyword: "Jialong, Jialong Blog, 嘉龙的博客"
url: "https://jialong-c.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Jialong-c/Jialong-c.github.io.git" # you code repository


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-JL.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# weibo_username:     
zhihu_username:     xiwanghuiyibushimeng
github_username:    jialong-c
#facebook_username:  
jianshu_username:    2923dd94f021
twitter_username:   WangJialong_




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b07769b7b66f441e2204                            #生成的clientID
  clientSecret: d98585dbd60b572224ca17b2fa0a7a69111b3ec5    #生成的clientSecret
  repo: jialong-c.github.io    #仓库名称
  owner: jialong-c    #github用户名
  admin: jialong-c
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

#
# Analytics settings
# Baidu Analytics
ba_track_id: e7bd6f6c75542cd6fd4fddf364edcd91

                    

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
#





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·JL",
        href: "https://www.jianshu.com/u/2923dd94f021"
    }
]

(function(window,document) {
    let hearts = [];
    window.requestAnimationFrame = (function() {
        return window.requestAnimationFrame ||
        window.webkitRequestAnimationFrame ||
        window.mozRequestAnimationFrame ||
        window.oRequestAnimationFrame ||
        window.msRequestAnimationFrame ||
        function (callback){
            setTimeout(callback, 1000 / 60);
        }
    })();
    init();
    setInterval(createHeart, 800);
    function init() {
        css(".heart{width: 10px;height: 10px;position: fixed;background: #f00;transform: rotate(45deg);-webkit-transform: rotate(45deg);-moz-transform: rotate(45deg);}.heart:after,.heart:before{content: '';width: inherit;height: inherit;background: inherit;border-radius: 50%;-webkit-border-radius: 50%;-moz-border-radius: 50%;position: absolute;}.heart:after{top: -5px;}.heart:before{left: -5px;}");
        attachEvent();
        gameloop();
    }
    function gameloop() {
        for (let i = 0; i < hearts.length; i++) {
            if (hearts[i].alpha <= 0) {
                document.body.removeChild(hearts[i].el);
                hearts.splice(i, 1);
                continue;
            }
            hearts[i].y--;
            hearts[i].scale += 0.005;
            hearts[i].alpha -= 0.005;
            hearts[i].el.style.cssText = "left:" + hearts[i].x + "px;top:" + hearts[i].y + "px;opacity:" + hearts[i].alpha + ";transform:scale(" + hearts[i].scale + "," + hearts[i].scale + ") rotate(45deg);background:" + hearts[i].color;
        }
        requestAnimationFrame(gameloop);
    }
    function attachEvent() {
        var old = typeof window.慰nclick === "function" && window.onclick;
        window.onclick = function(event) {
            old && old();
            createHeart(event);
        }
    }
    function createHeart(event) {
        if (document.getElementsByClassName('heart').length < 10) {
            var d = document.createElement("div");
            d.className = "heart";
            var x, y;
            if (event) {
                x = event.clientX - 5;
                y = event.clientY - 5;
            } else {
                var maxX = window.screen.availWidth,
                    maxY = window.screen.availHeight;

                x = Math.floor(Math.random() * (maxX + 1));
                y = Math.floor(Math.random() * (maxY + 1));
            }

            hearts.push({
                el : d,
                x : x,
                y : y,
                scale : 1,
                alpha : 1,
                color : randomColor()
            });
            document.body.appendChild(d);

        }
        
    }
    function css(css) {
        var style = document.createElement("style");
        style.type="text/css";
        try {
            style.appendChild(document.createTextNode(css));
        } catch(ex) {
            style.styleSheet.cssText = css;
        }
        document.getElementsByTagName('head')[0].appendChild(style);
    }
    function randomColor() {
        return "rgb(" + (~~(Math.random()*255)) + "," + (~~(Math.random()*255)) + "," + (~~(Math.random()*255)) + ")";
    }
})(window,document);    